# Generated by Django 2.0.6 on 2019-04-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='backend.Trip'),
        ),
    ]
